### ISSUE TITLE
User authentication solved

### ISSUE THREAD

**Issue by maxpipoka** [Rykiu/Trabajo-Practico-04#1]
Hola Ramiro, este middleware estaba interfiriendo en el funcionamiento.
Además de que en la request definida en el request.http habia una linea de espacio entre la url del endpoint y la definicion del Content-type por lo que no la tomaba como válida.

https://github.com/Rykiu/Trabajo-Practico-04/blob/e8b673d78c0a065e50ffaaf8d4725668ec72e29e/index.js#L13

https://github.com/Rykiu/Trabajo-Practico-04/blob/e8b673d78c0a065e50ffaaf8d4725668ec72e29e/request.http#L2

**Comment by Rykiu** [comment]
muchas gracias!!.
